### PR TITLE
Differential-datalog solution

### PR DESCRIPTION
**Pull request by qishen**
A Differential-datalog solution that uses a dialect of Datalog for modeling and works just fine but still slower than the native differential-dataflow solution.

### CODE REVIEW

**Comment by szarnyasg** [comment]
Hi, this is excellent, thank you! We have the benchmarking environment set up on a server so we can compare it right away with the other solutions.

For the PR, can you please add a short README that explains the difference between the `differential-datalog` and `differential-formula` solutions, and provides installation instructions?

Ideally, we would package this as a Docker image yet to make it simple to run in the benchmarking environment.

**Comment by marci543** [comment]
To evaluate the new tools in CI, please list them here:
https://github.com/TransformationToolContest/ttc2018liveContest/blob/38e95b49ef9cba51ecf234b9299a3827b2962139/docker/Dockerfile-differential#L15-L16
https://github.com/TransformationToolContest/ttc2018liveContest/blob/38e95b49ef9cba51ecf234b9299a3827b2962139/config/config-docker-differential.json#L7-L8

**Comment by qishen** [comment]
Thanks for the feedback and I'll add a README and figure out the setup on docker later. The differential-formula is broken right now so this PR is only for differential-datalog specifically ddlog v0.39 since they change APIs a lot. I may add a separate differential-formula solution whenever I fix it. I started with my own implementation with differential-dataflow to create a logic programming style modeling language but later found out ddlog is similar to what I want to do so I decided to add a ddlog solution to your benchmark first and see how it works.

**Comment by qishen** [comment]
Is it okay that I changed the minimum memory from 6GB to 1GB for all `solution.ini` in EMF solutions because my VM cannot allocate 6GB memory but the maximum is still set to 6GB untouched? It is in one of my commits in this PR and I may need to reverse it back to 6GB if you guys don't approve and have a good reason for it.

**Comment by szarnyasg** [comment]
Yes, it's fine. The script that executes the benchmark uses sed to replace
the memory settings in the solution.ini files.
Two things:
- Is this PR now good to review?
- Can you tell us more about your interest in this project? Feel free to
reach out through email (my address is in my profile).

**Comment by qishen** [comment]
Hey, I just cleaned up the legacy code and squashed them into fewer commits without touching other solutions and their configurations. I think this PR is ready for your guys to review now and let me know if there are any additional requirements for the benchmark. I'll send you an email later.

**Comment by qishen** [comment]
Any feedback or you need more time to review or should I close the PR? I ran the benchmark several times and the results are all correct.

**Comment by marci543** [comment]
Sorry for the delay. I will propose a few changes and send them today.

**Comment by marci543** [comment]
@qishen, can you please help me because I get this error message when I try to run it:
```Running benchmark: tool = differential-datalog, change set = 1, query = Q1
error: failed to get `differential_datalog` as a dependency of package `snq1_lib v0.1.0 (/ttc/solutions/differential-datalog/snq1/snq1_lib)`

Caused by:
  failed to load source for dependency `differential_datalog`

Caused by:
  Unable to update /ttc/solutions/differential-datalog/snq1/snq1_ddlog/differential_datalog

Caused by:
  failed to read `/ttc/solutions/differential-datalog/snq1/snq1_ddlog/differential_datalog/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
Traceback (most recent call last):
  File "scripts/run.py", line 176, in <module>
    benchmark(config)
  File "scripts/run.py", line 88, in benchmark
    raise subprocess.CalledProcessError(return_code, process.args,
subprocess.CalledProcessError: Command 'cd snq1/snq1_lib && cargo run -q --release -- HARNESS' returned non-zero exit status 101.```

**Comment by qishen** [comment]
```snq1_ddlog``` is the runtime generated by ```snq1.dl``` and serves as dependency for ```snq1_lib```. I guess you didn't create the runtime before running the benchmark. Try ```python run.py -b``` to build the runtime.

https://github.com/qishen/ttc2018liveContest/blob/9f5cd82d408995a298b2c55dffaecc78423701d9/solutions/differential-datalog/snq1/run.sh#L18-L22

**Comment by marci543** [comment]
Can you please check this sequence on the clean repo?
```bash
git clone --branch ddlog-solution https://github.com/qishen/ttc2018liveContest/
cd ttc2018liveContest/
sed -Ei '/"differential(-08)?"/d' config/config-docker-differential.json
./docker.sh --build --run --tags differential
```

**Comment by qishen** [comment]
I found the problem caused by the ```solution.ini``` where I didn't put commands under ```skipTests``` and now it's all good running in docker.

**Comment by marci543** [comment]
Thank you. I'll check.

I wanted to ask you whether this solution is multi-threaded or not.
I'm not familiar with Rust. Is multi-threaded mode the default? Or does it have to be turned on like this?
https://github.com/TransformationToolContest/ttc2018liveContest/blob/1a631d3be22a25d39e79eef4fff8a3a555c01732/solutions/differential-08/solution.ini#L6-L7

**Comment by qishen** [comment]
Yes, the parameters ```-w8``` means running the dataflow with 8 workers in 8 threads. It's not a Rust feature but a differential-dataflow feature and by default it uses only one worker.

**Comment by marci543** [comment]
Currently differential-datalog reaches the timeout in CI.
I merged a PR which extends the limit and checks whether the tools finish on time.

**Comment by qishen** [comment]
I don't know why it times out and fails in CI but there are no issues running on my machine as shown in the screenshot. 
 
微信图片_20210505180128

**Comment by marci543** [comment]
I'm still struggling with the issue that I want to make sure that all tools run completely but within a time limit and produce the correct results. See #101.
Sorry for this. I'll figure out.

**Comment by qishen** [comment]
By the way, CI was working and passed all the checks before I rebased to the latest master branch so I suspect there could be some problems within the last few commits and hope you figure it out.

**Comment by marci543** [comment]
Unfortunately before #101, the CI silently accepted if a tool reached timeout. This was the case for previous commits, e.g. in 84206e1956259b5c45eb3c44f90be925f907fde3 ([full log](https://github.com/TransformationToolContest/ttc2018liveContest/runs/2505344970)):
```
Running benchmark: tool = differential-datalog, change set = 1, query = Q1
Program reached the timeout set (60 seconds). The command we executed was 'cd snq1/snq1_lib && cargo run -q  -- HARNESS'
Running benchmark: tool = differential-datalog, change set = 1, query = Q2
Program reached the timeout set (60 seconds). The command we executed was 'cd snq2/snq2_lib && cargo run -q  -- HARNESS'
```

I tried to investigate and it looks like the timeout is only reached by the first and smallest run (4+ minutes).  The second run on bigger size finishes in 1-3 seconds. I would guess that there might be something missed during the build or built with another config, and the first runs also build the code not just run the query. (5778062a5ade21784f94dd10aaa72b517d17fcac, [full log](https://github.com/marci543/ttc2018liveContest/runs/2528419463))
```
Running benchmark: tool = differential-datalog, change set = 1, query = Q1
433.12user 21.23system 4:22.65elapsed 172%CPU (0avgtext+0avgdata 1774296maxresident)k
79376inputs+6640936outputs (140major+3280373minor)pagefaults 0swaps
Running benchmark: tool = differential-datalog, change set = 2, query = Q1
1.52user 0.08system 0:01.64elapsed 98%CPU (0avgtext+0avgdata 41652maxresident)k
16136inputs+0outputs (51major+5796minor)pagefaults 0swaps
Running benchmark: tool = differential-datalog, change set = 1, query = Q2
500.50user 22.15system 4:58.42elapsed 175%CPU (0avgtext+0avgdata 1717920maxresident)k
35688inputs+7971128outputs (79major+3518578minor)pagefaults 0swaps
Running benchmark: tool = differential-datalog, change set = 2, query = Q2
3.07user 0.14system 0:03.09elapsed 104%CPU (0avgtext+0avgdata 60012maxresident)k
10648inputs+0outputs (63major+8505minor)pagefaults 0swaps
```

**Comment by marci543** [comment]
@qishen, what do you think about the following changes?

- I removed the code of ddlog from the repo and download during the build process.
- I merged the separate `run.sh` files into `build.sh`.
- I added [sccache](https://github.com/mozilla/sccache). I think it speeds the compilation up because the two separate programs for the two queries have common dependencies.
- Builing the code in release mode is extremely slow (70 min.). I guess the optimization takes time.
I tried to use the default dev mode but it used up all available disk space (7fa3dcec10d6b62be7dd62a45c7ea8c9dffa5830, [log](https://github.com/marci543/ttc2018liveContest/actions/runs/817628647)). The current workaround is to use dev mode and disable emitting debug information when run in CI.
https://github.com/TransformationToolContest/ttc2018liveContest/blob/d8338e0733dd9926967cc5bcd70a01d4374ac0c6/solutions/differential-datalog/build.sh#L22
>Yes, the parameters -w8 means running the dataflow with 8 workers in 8 threads. It's not a Rust feature but a differential-dataflow feature and by default it uses only one worker.
- I added `-w$(nproc)` option to the `cargo run -q --release -- HARNESS` command, but it looks like only one thread is used. Can you please help me to turn multi-threading on?

**Comment by qishen** [comment]
LGTM except the parameter ```-w$(nproc)``` will be ignored because it's a feature only for ```differential-dataflow``` even though ```differential-datalog``` is built on top of it. Multi-thread ```differential-datalog``` is under development and I'll add it when the feature is stable. Good job thanks!

**Comment by marci543** [comment]
Thank you for the PR.
I've removed the commits that cancel each other out and will merge this once the CI finishes.

**Pull request merged**
