### PR TITLE
Change measurement order

### PR DESCRIPTION
**Pull request by marci543**
- change order of measurements
- throw exception again if a tool fails
- refactor argument handling

### CODE REVIEW

**Comment by szarnyasg** [comment]
+1

**Comment by agarciadom** [comment]
If I understood correctly this change, the old order was run - tool - change - query, and the new one is tool - query - change - run. While the new order reduces the number of times we need to read the configuration, the old one actually made it so we could "fail fast" if a tool was improperly configured/installed, or if it failed in one of the queries.

With the proposed order, we'd have to wait for all the runs of the previous tools to complete before we saw the first error message from a failing tool.

Any thoughts?

**Comment by szarnyasg** [comment]
@bluezio Thanks for your thoughts. I proposed this new order so that the benchmark campaigns run in the shortest possible time. Of course, this assumes that the solutions have been tried and tested beforehand.

**Comment by agarciadom** [comment]
Hmm, I guess that the solution authors would be expected to change the .json file so it had only their tool before submitting the PR. Let's merge this, then.

**Pull request merged**
