### PR TITLE
VIATRA and SQL solutions

### PR DESCRIPTION
**Pull request by szarnyasg**
*Ready to merge.*

I opened this for tracking changes and eventually merge them into master.

### CODE REVIEW

**Comment by georghinkel** [comment]
Is there any update on this pull request such that it is ready to merge?

**Comment by szarnyasg** [comment]
Hi @georghinkel - I missed this update, I was unsubscribed from the thread for some reason.
The VIATRA version is feature-complete and correct, but I'll do a round of reviews with one of the core developers.
@jmarton finished the incremental SQL version, but not yet the batch (non-incremental) implementation.

**Comment by jmarton** [comment]
@georghinkel I'm happy to tell that this branch is ready to merge, including both the Viatra and the SQL (batch and incremental) solutions

**Comment by agarciadom** [comment]
Thanks for this! Merging :-).

**Pull request merged**
