### PR TITLE
WeightedQuickUnionUF => WeightedQuickUnionPathCompressionUF

### PR DESCRIPTION
**Pull request by arturboronat**
This makes union and find faster: with amortized cost, almost O(1), instead of log(n).

Tested locally and ready for merge.

### CODE REVIEW

**Comment by arturboronat** [comment]
If I spot improvements, I'll keep pushing them to this PR. Let me know when you are planning to launch the next run of the benchmark. Thanks!

**Comment by marci543** [comment]
The benchmark has finished. If you want, I can rerun it on EMFSolutionYAMTL* solutions.

**Comment by arturboronat** [comment]
Many thanks for the wait. I have added a parallelized variant of EMFSolutionYAMTL_expl in  EMFSolutionYAMTL_expl_parallel. This variant uses the experimental parallel pattern matcher of YAMTL. Please execute: 

- EMFSolutionYAMTL
- EMFSolutionYAMTL_batch
- EMFSolutionYAMTL_expl
- EMFSolutionYAMTL_expl_parallel

**Comment by marci543** [comment]
Should I merge this PR now?

**Comment by arturboronat** [comment]
Please do so. Thanks!

**Pull request merged**
