### PR TITLE
Downgrade YAMTL

### LINKED ISSUE #51: Java versions
Followup of issues #40 and #50.

I am trying to collect the required Java versions:

* `differential*`: 8/11
* `EMFSolutionAOF`: 8 
* `EMFSolutionATL*`: 8
* `EMFSolutionViatra`: 8/11?
* `EMFSolutionXtend`: 8/11
* `EMFSolutionYAMTL*`: 11 (!)
* `Hawk*`: 8/11
* `GraphBLAS`: 8/11
* `jastadd-ttc18*`: 8
* `Naiad*`: -
* `Neo4j*`: 8 (might work with 11 but not officially supported)
* `NMF*`: -
* `SQLSolution*`: 8/11

### PR DESCRIPTION
**Pull request by szarnyasg**
@arturboronat please review this.

**Update: unfortunately, it doesn't seem to work, see below.**

### CODE REVIEW

**Comment by agarciadom** [comment]
Waiting on review by @arturboronat.

**Comment by szarnyasg** [comment]
Unfortunately, this seems that these changes only work if Java 11 is running - while the point of this would be to run everything on Java 8.

```bash
$ sdk use java 8.0.222.hs-adpt

Using java version 8.0.222.hs-adpt in this shell.

$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

$ ./gradlew clean fatJar

> Task :compileJava FAILED
/home/szarnyasg/git/ttc/ttc2018liveContest/solutions/EMFSolutionYAMTL/src/main/xtend-gen/ttc2018/LiveContestDriver.java:24: error: cannot access Delta
import yamtl.core.Delta;
                 ^
  bad class file: /home/szarnyasg/.gradle/caches/modules-2/files-2.1/yamtl/yamtl/0.0.3-SNAPSHOT/48075408b07bffef2078c8d3a47a3da6ffdbc166/yamtl-0.0.3-SNAPSHOT.jar(yamtl/core/Delta.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 2 executed, 1 up-to-date
```

So we might have to go with a mixed setup after all.

**Comment by arturboronat** [comment]
This has now been solved. Please check #63

**Comment by agarciadom** [comment]
#59 fixed an issue with CI over .NET. Could you rebase this PR on top of the latest `master`?

**Pull request merged**
