### PR TITLE
Fail on timeout in CI

### PR DESCRIPTION
**Pull request by marci543**
This PR adds `--error-on-timeout` option to `scripts/run.py`. CI fails if a tool reaches timeout.

@bluezio
I separated the run of `HawkNeo4J` in CI and only run it on size 1 since size 2 would need more than 10 minutes.
Relevant commit: 81e6e7bdf0edb1f50b14d452097fea5d33acebaf

### CODE REVIEW

**Comment by agarciadom** [comment]
This is odd - Neo4j takes ~12-15s for size 2 in my laptop. I'll investigate further later - thanks for the tip.

**Comment by marci543** [comment]
I tried to find a good timeout with no luck (see red marks at [Actions](https://github.com/TransformationToolContest/ttc2018liveContest/actions)).
I think I will run the batch versions (Hawk, HawkNeo4J, HawkSQLite) only on size 1.

HawkNeo4J behaves strange also during the benchmark. See `output/details/output/log-2021-05-03T17.47.10.log` in the paper repo. It ran 4 times below the timeout (10 min.) but reached it at the 5th measurement on both queries and size 2.

**Comment by szarnyasg** [comment]
I visualized the latest results:

[results-hawk.pdf](https://github.com/TransformationToolContest/ttc2018liveContest/files/6429363/results-hawk.pdf)

**Comment by marci543** [comment]
I will merge this to enforce all tools to finish on time in CI. I hope the tests won't be flaky.

I will open an issue for the strange behaviour of batch Hawk variants especially Neo4j.

**Pull request merged**
