### PR TITLE
Naiad solution

### PR DESCRIPTION
**Pull request by szarnyasg**
*Ready to merge.*

Only merge after #17.

### CODE REVIEW

**Comment by szarnyasg** [comment]
Is this ready to merge @antaljanosbenjamin ?

**Comment by antaljanosbenjamin** [comment]
@szarnyasg I think it's ready to merge!

**Comment by szarnyasg** [comment]
Looks good to me, thanks!

**Comment by agarciadom** [comment]
Merging, then!

**Pull request merged**
