### PR TITLE
new version of jastadd solution(s)

### PR DESCRIPTION
**Pull request by rene-schoene**
## Updated JastAdd solutions to removal of Comment.Post

- Updated used dependencies including jastadd and relast
- Updated to use Java11 (not reflected in the configs yet)

### CODE REVIEW

**Comment by rene-schoene** [comment]
Would it be beneficial to also put in the source code used for building the solution(s)?

**Comment by szarnyasg** [comment]
Sure, I see no reason not to include the source code. The best setup is when users can rebuild it themselves based on the instructions in `solution.ini`. But even if this is not possible, it would be good to include the source code.

**Comment by marci543** [comment]
I moved JustAdd to the java11 image. It works now.

**Comment by szarnyasg** [comment]
One question: which JastAdd version is this? (I'm updating the table in the paper)

**Comment by rene-schoene** [comment]
was also on my todo-list to update the table (along with fixing the description after removal of `rootPost`) :slightly_smiling_face: 
JastAdd version is `2.3.5`

also, we had an idea for a new variant of our solution, and are currently testing its performance. I'll update this PR accordingly this week. when do you want to start the benchmark?

**Comment by szarnyasg** [comment]
I bumped the versions in the table - please review them. I'm not sure
JastAdd itself requires Java 11 or 8 is also fine,

Benchmarking - this weekend or next week. So we wait for the PR.

**Comment by rene-schoene** [comment]
I've updated the solutions to include the new variant(s), and removed two of the old variants (the namelookup ones, which were also not described in the paper).
I'll update the paper "soon" to describe the variants.

Interestingly, the non-incremental version performed better than the incremental of the new variant, in a small benchmark (one run only, and assuming I did not mess up the diagram) :thinking: 
image

**Comment by szarnyasg** [comment]
Thanks. Interesting. Incremental variants can be beaten by a batch solution if the change is large (in proportion to the full graph) but I'm not sure this is the case here.

Could you please include the source code of the JastAdd solutions in this PR?

**Comment by rene-schoene** [comment]
I've add the source. However, it is not the complete project, as this involves symlinks between gradle-files and other stuff that would be messed up by the different directory structure. The complete source code is in our repository at <https://git-st.inf.tu-dresden.de/stgroup/ttc18live> (which is public, cited in the original paper, and in the README of all (sub-) solutions here.

Is this OK for you?

**Comment by szarnyasg** [comment]
Yes, this is okay. Thanks!

**Comment by szarnyasg** [comment]
@rene-schoene we ran a benchmark with @marci543 and visualized the results.
These show that the performance characteristics during the Initial/Update phases are primarily determined by XML vs reusable and not by being a batch vs an incremental variant. This is a bit suspicious to me. Can you please double-check the tool names and setup used?

[results-jastadd.pdf](https://github.com/TransformationToolContest/ttc2018liveContest/files/6361601/results-jastadd.pdf)

**Comment by marci543** [comment]
Here are the [detailed numbers](https://github.com/TransformationToolContest/ttc2018liveContest/files/6361609/output-docker-2021-04-22T16.29.58-java11.zip).

**Pull request merged**
