### PR TITLE
Neo4j solution

### PR DESCRIPTION
**Pull request by szarnyasg**
~Do not merge yet.~ Please merge

### CODE REVIEW

**Comment by agarciadom** [comment]
This branch needs to be rebased on top of `master`.

**Comment by szarnyasg** [comment]
I tried to rebase it but the branch diverged way too much - I've spent half an hour manually merging files but realized that having a merge commit might be a cleaner approach here.

**Comment by agarciadom** [comment]
OK, sounds good. Let me know when it's ready to merge!

**Comment by szarnyasg** [comment]
@bluezio this is good to merge, please proceed

**Comment by szarnyasg** [comment]
This PR is good to go @bluezio

**Pull request merged**
