### PR TITLE
YAMTL solutions compatible with Java 8

### PR DESCRIPTION
**Pull request by arturboronat**

### CODE REVIEW

**Comment by szarnyasg** [comment]
Thanks.
@bluezio - the CI failure here is probably caused by a timeout, can you restart the job on Travis?

**Comment by agarciadom** [comment]
#59 fixed an issue with CI over .NET. Could you rebase this PR on top of the latest `master`?

**Comment by agarciadom** [comment]
This branch is conflicting with `master` - please rebase.

**Comment by agarciadom** [comment]
This branch is still failing its Travis checks, and it still needs to be rebased on top of the latest `master`.

**Comment by szarnyasg** [comment]
@arturboronat shall we close this since we're now using Docker images? (#69)

**Comment by agarciadom** [comment]
Let's close this - it's not an issue anymore with the Dockerized build.

**Pull request closed without merging**
